### PR TITLE
Update p210n-fdm.xml

### PR DESCRIPTION
**Pull request by ysopflying**
A few adaptions for the linear behavior. A lot of things left to do.

### CODE REVIEW

**Comment by TheFGFSEagle** [comment]
Whyever can't I merge this pull request ?

**Comment by ysopflying** [comment]
Github learning curve ;-)
I could merge, hopefully it worked.

**Comment by TheFGFSEagle** [comment]
Umm, actually you only merged the commits back into your own repository ! 😆️ But I was able to merge it successfully. How did you create these pull requests ?

Anyways -
The AeroRP was set to the location of the wings - whyevery should that be changed ?
Also, the reservoir fuel tanks are not located below the wings … but rather below the pilot's and copilot's feet. I will fix that after pulling.

**Comment by TheFGFSEagle** [comment]
Uh, sorry for my complaint about the reservoir tanks … they indeed should not be located below the propeller … 😆️

**Pull request merged**
